[package]
name = "wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
#tokio = { version = "1.0", features = ["full"] }
utility = { path = "../utility" }
maintx = { path = "../maintx" }
