[package]
name = "maincore"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
thiserror = "1.0"
utility = { path = "../utility" }
maintx = { path = "../maintx" }
